export  interface cocktaildata {
    dateModified: string,
    idDrink: string,
    strAlcoholic: string,
    strCategory: string,
    strCreativeCommonsConfirmed: string,
    strDrink: string,
    strDrinkThumb: string,
    strGlass: string,
    strIngredient1: string,
    strIngredient2: string,
    strIngredient3: string,
    strInstructions: string,
    strInstructionsDE: string,
    strInstructionsIT: string,
    strMeasure1: string,
    strMeasure2: string,
    strMeasure3: string,
}
